name: Сборка
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: alpine:3.21.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up environment
        run:
          apk add openjdk21
          apk add nodejs

      - name: Build
        run: |
          ./gradlew build

      - name: Prepare Docker artifacts
        run: |
          mkdir -p /tmp/artifacts
          cp build/libs/cdkl5-all.jar /tmp/artifacts/app.jar
          cp Dockerfile /tmp/artifacts/

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: output
          key: ${{ runner.os }}-artifact-cache

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Runs on host (not in a container)

    steps:
      - name: Download artifacts
        uses: actions/cache@v3
        with:
          path: output
          key: ${{ runner.os }}-artifact-cache

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PUBLIC_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Docker host
        run: |
          scp -r . ${{ secrets.SSH_ADDRESS}}:/tmp/deploy/
          ssh ${{ secrets.SSH_ADDRESS}} "
            cd /tmp/deploy
            docker build -t cdkl5:latest .
            docker stop cdkl5 || true
            docker rm cdkl5 || true
            docker run -d --name cdkl5 -p 8080:8080 cdkl5:latest