name: Сборка
on:
  push:
jobs:
  build-test:
    name: Test context
    runs-on: ubuntu-cloud-runner
    container:
      gradle:ubi-minimal
    steps:
      - name: Build
        uses: actions/checkout@v3  # Checkout the repository code
        run: |
          ./gradlew build