name: Сборка
on:
  push:
jobs:
  build-test:
    name: Test context
    runs-on: ubuntu-cloud-runner
    container:
      gradle:jdk17-alpine
    steps:
      - name: Checkout
        run: |
          git clone https://gitverse.com/${{ gitverse.repository }}
          git checkout ${{ github.sha }}
      - name: Build
        run: |
          ./gradlew build